Vagrant.configure(2) do |config|
  config.vm.hostname = "angular-express-postgres-dev-server"
  config.vm.box = "ubuntu/trusty32"

  # port forwarding
  config.vm.network :forwarded_port, host_ip: "0.0.0.0", host: 15432, guest: 5432 #postgresql
  config.vm.network :forwarded_port, host_ip: "0.0.0.0", host: 19200, guest: 9200 #elasticsearch
  config.vm.network :forwarded_port, host_ip: "0.0.0.0", host: 16379, guest: 6379 #redis

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # provision
  config.vm.provision :shell, :path => "bootstrap.sh"
end
