Vagrant.configure("2") do |config|
  config.vm.hostname = "angular-express-webapp-base-dev-server"
  config.vm.box = "trusty-server-cloudimg-amd64-vagrant-disk1"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  # port forwarding
  config.vm.network :forwarded_port, host_ip: "0.0.0.0", host: 15432, guest: 5432 #postgresql
  config.vm.network :forwarded_port, host_ip: "0.0.0.0", host: 19200, guest: 9200 #elasticsearch
  config.vm.network :forwarded_port, host_ip: "0.0.0.0", host: 16379, guest: 6379 #redis

  # configure machine properties
  config.vm.provider "virtualbox" do |v|
    v.name = "Angular+Express webapp base development server"
    v.customize ["modifyvm", :id, "--memory", "1024"]
    v.customize ["modifyvm", :id, "--cpus", "1"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--pae", "on"]
    v.customize ["modifyvm", :id, "--hwvirtex", "on"]
    v.customize ["modifyvm", :id, "--rtcuseutc", "on"]
    v.customize ["modifyvm", :id, "--accelerate3d", "off"]
    v.customize ["modifyvm", :id, "--vram", "12"]

    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  # provision
  config.vm.provision :shell, :path => "bootstrap.sh"
end
